### PR TITLE
添加日志模式

### PR DESCRIPTION
**Pull request by proxy666-dev**
添加日志模式。

### CODE REVIEW

**Comment by proxy666-dev** [comment]
我提了没人解决，没办法，我只能自己解决了。

**Comment by mrli20182018** [comment]
> 我提了没人解决，没办法，我只能自己解决了。

你好 请问如何使用？
image

没有看到日志文件

**Comment by proxy666-dev** [comment]
@mrli20182018 你的用法不对，正确的用法是:-LM=file:/filepath/file.log或者-LM=shell:stdout

**Comment by proxy666-dev** [comment]
diff --git a/gost/cmd/gost/main.go b/gost/cmd/gost/main.go
index f08f413..4c886fa 100644
--- a/gost/cmd/gost/main.go
+++ b/gost/cmd/gost/main.go
@@ -16,6 +16,7 @@ import (
 )
 
 var (
+	LogMode string
 	configureFile string
 	baseCfg       = &baseConfig{}
 	pprofAddr     string
@@ -31,6 +32,7 @@ func init() {
 
 	flag.Var(&baseCfg.route.ChainNodes, "F", "forward address, can make a forward chain")
 	flag.Var(&baseCfg.route.ServeNodes, "L", "listen address, can listen on multiple ports (required)")
+	flag.StringVar(&LogMode, "LM", "", "log mode")
 	flag.StringVar(&configureFile, "C", "", "configure file")
 	flag.BoolVar(&baseCfg.Debug, "D", false, "enable debug log")
 	flag.BoolVar(&printVersion, "V", false, "print version")
@@ -45,6 +47,8 @@ func init() {
 		os.Exit(0)
 	}
 
+	gost.SetLogMode(LogMode)
+
 	if configureFile != "" {
 		_, err := parseBaseConfig(configureFile)
 		if err != nil {
diff --git a/gost/log.go b/gost/log.go
index d4ad519..5981435 100644
--- a/gost/log.go
+++ b/gost/log.go
@@ -3,8 +3,31 @@ package gost
 import (
 	"fmt"
 	"log"
+	"strings"
+	"os"
 )
 
+//设置日志模式
+func SetLogMode(LogMode string) {
+	if LogMode != "" {
+	var split []string = strings.Split(LogMode, ":")
+	if split[0] == "file" {
+    logFile, err := os.OpenFile(split[1], os.O_RDWR | os.O_CREATE | os.O_APPEND, 0770)
+    if err != nil {
+        panic(err.Error())
+    } else {
+        log.SetOutput(logFile)
+    }
+    //defer logFile.Close()
+	}
+	if split[0] == "shell" {
+	if split[1] == "stdout" {
+	log.SetOutput(os.Stdout)
+	}
+	}
+	}
+}
+
 func init() {
 	log.SetFlags(log.LstdFlags | log.Lshortfile)
 }

**Comment by muskminer** [comment]
用json启动，文件怎么写？

**Pull request closed without merging**
